export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const PROFILE_LOADING = 'PROFILE_LOADING';